# Generated by Django 2.2.5 on 2019-10-22 04:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=255)),
                ('category_summary', models.CharField(max_length=255)),
                ('category_slug', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ProductManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_manufacturer', models.CharField(max_length=255)),
                ('manufacturer_summary', models.CharField(max_length=255)),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.ProductCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(default='')),
                ('uploadDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date uploaded')),
                ('product_slug', models.CharField(default=1, max_length=255)),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.ProductCategory', verbose_name='Category')),
                ('product_manufacturer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.ProductManufacturer', verbose_name='Manufacturer')),
            ],
        ),
    ]
